Traceback (most recent call last):
  File "C:\Users\MRH\AppData\Roaming\Python\Python312\site-packages\jupyter_core\utils\__init__.py", line 154, in wrapped
    asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MRH\AppData\Roaming\Python\Python312\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\MRH\AppData\Roaming\Python\Python312\site-packages\nbclient\client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MRH\AppData\Roaming\Python\Python312\site-packages\jupyter_core\utils\__init__.py", line 158, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\asyncio\base_events.py", line 691, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\MRH\AppData\Roaming\Python\Python312\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "C:\Users\MRH\AppData\Roaming\Python\Python312\site-packages\nbclient\client.py", line 1005, in async_execute_cell
    exec_reply = await self.task_poll_for_reply
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MRH\AppData\Roaming\Python\Python312\site-packages\nbclient\client.py", line 806, in _async_poll_for_reply
    error_on_timeout_execute_reply = await self._async_handle_timeout(timeout, cell)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MRH\AppData\Roaming\Python\Python312\site-packages\nbclient\client.py", line 856, in _async_handle_timeout
    raise CellTimeoutError.error_from_timeout_and_cell(
nbclient.exceptions.CellTimeoutError: A cell timed out while it was being executed, after 30 seconds.
The message was: Cell execution timed out.
Here is a preview of the cell contents:
-------------------
['from sklearn.model_selection import train_test_split', 'from sklearn.preprocessing import StandardScaler', 'from sklearn.naive_bayes import GaussianNB', 'from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix', '']
...
["    if data['Present'][i] + data['Absent'][i] > data['Enrolled'][i]:", "        data['Absent'][i] = data['Enrolled'][i] - data['Present'][i]", "data['Released_Early'] = [data['Enrolled'][i] - data['Present'][i] - data['Absent'][i] for i in range(n)]", '', 'df = pd.DataFrame(data)']
-------------------

